name: Bug Report
description: File a bug report
title: "[Bug]: "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help improve this project!

  - type: checkboxes
    id: latest
    attributes:
      label: I've read the documentation:
      options:
        - label: I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
          required: true
        - label: I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.
          required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: On what operating system are you running Tube Archivist on?
      placeholder: ex. Linux, Unraid, Synology...
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Your Bug Report
      value: "## Describe the bug\n\n## Steps To Reproduce\n\n## Expected behavior"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant Docker logs. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
