name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip wheel
      - run: pip install bandit black codespell flake8 flake8-bugbear
                         flake8-comprehensions isort
      - run: bandit --recursive  --skip B105,B108,B404,B603,B607 .
      - run: black --check --diff --line-length 79 .
      - run: codespell
      - run: flake8 . --count --max-complexity=16 --max-line-length=79
                      --show-source --statistics
      - run: isort --check-only --line-length 79 --profile black .
      # - run: pip install -r tubearchivist/requirements.txt
      # - run: mkdir --parents --verbose .mypy_cache
      # - run: mypy --ignore-missing-imports --install-types --non-interactive .
      # - run: python3 tubearchivist/manage.py test || true
      # - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      # - run: safety check
